### ISSUE TITLE
Working on Due?

### ISSUE THREAD

**Issue by sickchilldownloads** [italo-coelho/pushButton#1]
I see it has "architectures=avr" in library.properties. Any chance this also works with a Due?

**Comment by italo-coelho** [comment]
> 

It should work well, but it was not tested. Please give a feedback if you were able to use it properly.

**Comment by sickchilldownloads** [comment]
I couldn't get it to work reliably for some reason. Button code and a circuit using a 74HC4067 working perfectly on the Mega compiled on the Due after adapting the library.properties file to "architectures=*". But immediately after uploading the buttons went high once one after another and then stopped responding. After connecting the buttons directly without a multiplexer it did MOSTLY work, but I occasionally saw some buttons go high by themselves, as well. No luck for me. Thanks!
